/* This file is automatically generated by gulp. */
(function() {
  'use strict';

  angular
  .module('pad-thai')
  .constant('pad-thai.config.genres', {
    'ALTERNATIVE_ROCK': 'Alternative Rock',
    'AMBIENT': 'Ambient',
    'CLASSICAL': 'Classical',
    'COUNTRY': 'Country',
    'DANCE_AND_EDM': 'Dance & EDM',
    'DANCEHALL': 'Dancehall',
    'DEEP_HOUSE': 'Deep House',
    'DISCO': 'Disco',
    'DRUM_AND_BASS': 'Drum & Bass',
    'DUBSTEP': 'Dubstep',
    'ELECTRONIC': 'Electronic',
    'FOLK_AND_SINGER_SONGWRiTER': 'Folk & Singer-Songwriter',
    'HIP_HOP_AND_RAP': 'Hip Hop & Rap',
    'HOUSE': 'House',
    'INDIE': 'Indie',
    'JAZZ_AND_BLUES': 'Jazz & Blues',
    'LATIN': 'Latin',
    'METAL': 'Metal',
    'PIANO': 'Piano',
    'POP': 'Pop',
    'R_AND_B_SOUL': 'R&B & Soul',
    'REAGGE': 'Reggae',
    'REAGGAETON': 'Reggaeton',
    'ROCK': 'Rock',
    'SOUNDTRACK': 'Soundtrack',
    'TECHNO': 'Techno',
    'TRANCE': 'Trance',
    'TRAP': 'Trap',
    'TRIP_HOP': 'Trip Hop',
    'WORLD': 'World'
  });

})();
