/* This file is automatically generated by gulp. */
(function() {
  'use strict';

  angular
  .module('pad-thai')
  .constant('pad-thai.config.weather-types', {
    types: {
      'SUNNY': 'Sunny',
      'FAIR': 'Fair',
      'CLOUDY': 'Cloudy',
      'PARTLY_CLOUDY': 'Partly cloudy',
      'FOG': 'Fog',
      'LIGHT_RAIN': 'Light rain',
      'MEDIUM_RAIN': 'Medium rain',
      'HEAVY_RAIN': 'Heavy rain',
      'THUNDER': 'Thunder',
      'LIGHT_SNOW': 'Light snow',
      'MEDIUM_SNOW': 'Medium snow',
      'HEAVY_SNOW': 'Heavy snow',
      'SNOW_AND_RAIN': 'Snow & rain'
    }
  });

})();
