module.exports = function(){
  'use strict';

  var CDN_URL = '';

  var SRC_FOLDER = 'frontend/src/';
  var MODULES_FOLDER = SRC_FOLDER + 'modules/';
  var FILES_FOLDER = SRC_FOLDER + 'files/';
  var REPORTS_FOLDER = FILES_FOLDER + 'reports/';
  var IMAGES_FOLDER = FILES_FOLDER + 'img/';
  var LESS_FOLDER = FILES_FOLDER + 'less/';
  var FONTS_FOLDER = FILES_FOLDER + 'fonts/';
  var BOWER_FOLDER = FILES_FOLDER + 'bower_components/';

  var TEMP_FOLDER = SRC_FOLDER + '.tmp/';
  var TEMP_CSS_FOLDER = TEMP_FOLDER + 'css/';
  
  var DIST_FOLDER = 'frontend/dist/';
  var REPORTS_DIST_FOLDER = DIST_FOLDER + 'reports/';
  var IMAGES_DIST_FOLDER = DIST_FOLDER + 'img/';
  var FONTS_DIST_FOLDER = DIST_FOLDER + 'fonts/';
  
  var ENVIRONMENTS_FOLDER = SRC_FOLDER + 'environment/';

  var ANGULAR_APP_NAME = 'pad-thai';

  return {
    ANGULAR_APP_NAME: ANGULAR_APP_NAME,
    SRC_FOLDER: SRC_FOLDER,
    REPORTS_FOLDER: REPORTS_FOLDER,
    MODULES_FOLDER: MODULES_FOLDER,
    FILES_FOLDER: FILES_FOLDER,
    IMAGES_FOLDER: IMAGES_FOLDER,
    LESS_FOLDER: LESS_FOLDER,
    BOWER_FOLDER: BOWER_FOLDER,
    TEMP_FOLDER: TEMP_FOLDER,
    TEMP_CSS_FOLDER: TEMP_CSS_FOLDER,
    DIST_FOLDER: DIST_FOLDER,
    IMAGES_DIST_FOLDER: IMAGES_DIST_FOLDER,
    FONTS_DIST_FOLDER: FONTS_DIST_FOLDER,
    REPORTS_DIST_FOLDER: REPORTS_DIST_FOLDER,
    CDN_URL: CDN_URL,
    ENVIRONMENTS_FOLDER: ENVIRONMENTS_FOLDER,
    FONTS_FOLDER: FONTS_FOLDER
  };
}; 
